#:kivy 1.9.0
#:import magic magic

<MagicLayout>
    id: magic_layout
    orientation: 'vertical'

    Button:
        id: magic_change
        text: "Change text below to text above"
        on_press: magic_layout.change_text()

    Label:
        id: magic_text
        text: "Should change to text from id: important_text"


FooScreen:
    id: magic_screen
    name: 'Magic'

    MagicLayout
